FROM rust:1.84 as builder

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev && \
    rustup target add x86_64-unknown-linux-gnu

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
RUN cargo fetch

COPY . .

RUN cargo build --release --target=x86_64-unknown-linux-musl \
    RUSTFLAGS="-C link-args=-lpq -lpthread -lssl -lcrypto"

FROM alpine:latest

RUN apk add --no-cache libpq

WORKDIR /app

COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/quiz /app/

CMD ["./quiz"]
