name: front

on:
  pull_request:
    paths:
      - "front/**"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.12.1"

      - name: Install dependencies
        run: |
          cd front
          yarn install

      - name: Run Lint
        run: |
          cd front
          yarn lint

      - name: Run Tests
        run: |
          cd front
          yarn test
